DROP DATABASE IF EXISTS vehicle;
SET FOREIGN_KEY_CHECKS=0;
CREATE DATABASE vehicle CHARACTER SET utf8mb4;
USE vehicle;

CREATE TABLE car (
	licensePlate VARCHAR(100) PRIMARY KEY,
	make VARCHAR(100),
	model VARCHAR(100),
	year INT UNSIGNED	
);

INSERT INTO car VALUES("654-YUE","Ford", "Fiesta", 2020);